openapi: 3.0.0
info:
  title: SmartHome - Client API
  version: 1.0.0
  description: >-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification. 
    You can find out more about

    Swagger at [https://swagger.io](https://swagger.io). In the third iteration
    of the pet store, we've switched to the design first approach!

    You can now help us improve the API whether it's by making changes to the
    definition itself or to the code.

    That way, with time, we can improve the API in general, and expose some of
    the new features in OAS3.


    Some useful links:

    - [The Pet Store
    repository](https://github.com/swagger-api/swagger-petstore)

    - [The source API definition for the Pet
    Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)


    Contact Support:
     Email: apiteam@swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
paths:
  /house/{houseId}/saved/temperature:
    get:
      summary: Returns saved temperature measurements
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    measuredAt:
                      type: string
                    value:
                      type: number
                    sensorID:
                      type: integer
              example:
                - measuredAt: 20225-12-01
                  value: 22.2
                  sensorID: 3245
                - measuredAt: 20225-12-02
                  value: 21.9
                  sensorID: 3245
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
              example:
                code: string
                message: string
      tags:
        - house/saved
      security:
        - ApiKeyAuth: []
      description: Returns a map of status codes to quantities.
    parameters:
      - name: houseId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: string
  /house/{houseId}/saved/video:
    get:
      summary: Returns saved video captures
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    createdAt:
                      type: string
                    data:
                      type: string
                    sensorID:
                      type: integer
              example:
                - createdAt: 20225-12-01
                  data: 6bdedsfloremipsum
                  sensorID: 3067
                - measuredAt: 20225-12-02
                  value: 6bdedsfloremipsum
                  sensorID: 3067
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
              example:
                code: string
                message: string
      tags:
        - house/saved
      description: >-
        For valid response try integer IDs with value <= 5 or > 10. Other values
        will generate exceptions.
    parameters:
      - name: houseId
        in: path
        required: true
        schema:
          type: string
        example: string
  /user/login:
    get:
      summary: Logs user into the system.
      parameters:
        - name: username
          in: query
          description: The user name for login
          schema:
            type: string
          example: string
        - name: password
          in: query
          description: The password for login in clear text
          schema:
            type: string
          example: string
      responses:
        '200':
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
              example: '2860'
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
              example: '1969-12-12T10:15:24.898Z'
          content:
            application/json:
              schema:
                type: object
              example: string
        '400':
          description: Invalid username/password supplied
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
              example:
                code: string
                message: string
      tags:
        - user
      description: Log into the system.
  /user/logout:
    get:
      summary: Logs out current logged in user session.
      responses:
        '200':
          description: successful operation
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
              example:
                code: string
                message: string
      tags:
        - user
      description: Log user out of the system.
  /user:
    post:
      summary: Create user.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                    format: email
                  password:
                    type: string
                    format: utc-millisec
                  phone:
                    type: string
                    format: utc-millisec
                  userStatus:
                    type: integer
              example:
                id: 10
                username: theUser
                firstName: John
                lastName: James
                email: john@email.com
                password: '12345'
                phone: '12345'
                userStatus: 1
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
              example:
                code: string
                message: string
      tags:
        - user
      description: This can only be done by the logged in user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                username:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: utc-millisec
                phone:
                  type: string
                  format: utc-millisec
                userStatus:
                  type: integer
            example:
              id: 10
              username: theUser
              firstName: John
              lastName: James
              email: john@email.com
              password: '12345'
              phone: '12345'
              userStatus: 1
  /user/{id}:
    get:
      summary: Get user by id
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                    format: email
                  password:
                    type: string
                    format: utc-millisec
                  phone:
                    type: string
                    format: utc-millisec
                  userStatus:
                    type: integer
              example:
                id: 10
                username: theUser
                firstName: John
                lastName: James
                email: john@email.com
                password: '12345'
                phone: '12345'
                userStatus: 1
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
              example:
                code: string
                message: string
      tags:
        - user
      description: Get user detail based on username.
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    put:
      summary: Update user resource.
      responses:
        '200':
          description: successful operation
        '400':
          description: bad request
        '404':
          description: user not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
              example:
                code: string
                message: string
      tags:
        - user
      description: This can only be done by the logged in user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                username:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: utc-millisec
                phone:
                  type: string
                  format: utc-millisec
                userStatus:
                  type: integer
            example:
              id: 10
              username: theUser
              firstName: John
              lastName: James
              email: john@email.com
              password: '12345'
              phone: '12345'
              userStatus: 1
    delete:
      summary: Delete user resource.
      responses:
        '200':
          description: User deleted
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
              example:
                code: string
                message: string
      tags:
        - user
      description: This can only be done by the logged in user.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: api_key
